### ISSUE TITLE
verification can get stuck

### ISSUE THREAD

**Issue by foldleft** [element-hq/element-web#12458]
I bailed out of a verification after sending a request.  I can no longer send new verification requests to that user – I get stuck on a spinner
<img width="361" alt="Screenshot 2020-02-21 at 14 15 30" src="https://user-images.githubusercontent.com/3935731/75041604-cee23880-54b4-11ea-971d-9c940967613b.png">

**Comment by foldleft** [comment]
It's possible that there's a request that it considers to be "in flight" – a few moments later the panel looks different:
<img width="346" alt="Screenshot 2020-02-21 at 14 20 15" src="https://user-images.githubusercontent.com/3935731/75041849-4ca64400-54b5-11ea-833e-56e0da85a0ea.png">

**Comment by bwindels** [comment]
Yeah, we should probably have a cancel button when there is a spinner.

I assume when you took the second screenshot, you actually saw a toast for that request on the other end?

**Comment by foldleft** [comment]
I didn't.  Also the change in text may be because I was running a stale client, I am presently poking at this to try to clarify the ticket

**Comment by foldleft** [comment]
One way to repro: get the verification into the `started` state, then refresh both browsers.  Now if you try to resume, it gets stuck on the spinner.

**Comment by bwindels** [comment]
this might be caused by the same reason as https://github.com/vector-im/riot-web/issues/12463, still investigating atm

**Comment by bwindels** [comment]
I just merged a fix for https://github.com/vector-im/riot-web/issues/12463, could you please try and see if you still repro once that get deployed on /develop?

**Comment by foldleft** [comment]
We still get stuck, but now progress happens once the other client also continues with the process

**Comment by yarikoptic** [comment]
not sure if the same issue, but hated to add one more "verification doesn't work".  I was trying to confirm session in Version 80.0.3987.162 (Developer Build) built on Debian 10.3, running on Debian bullseye/sid (64-bit) on my phone. Proceeded with emojies, confirmed on both ends, phone riot went back to chat, but in the browser it kept

Incoming Verification Request
Waiting for partner to confirm...

spinning

**Comment by yarikoptic** [comment]
and with "legacy verification" completed on the phone, nothing changed in the browser staying there in "Verify this login" screen

**Comment by jryans** [comment]
@yarikoptic It sounds unrelated to me, perhaps it was an issue with Riot Android instead of RiotX...? Please file a new issue so we can investigate separately.

**Comment by ShadowJonathan** [comment]
Can reproduce, following steps;
- Click user in members list
- Click "Start Verification"
- Reload/kill tab
- Go back to user -> verify
- Observe

This can however be "broken out" of by clicking `i` -> `x` -> `i`, after which it says "verification cancelled".

Also, the back button does not respond in any way when in the "verification" process.

I concur with @bwindels's suggestion, there should also be an explicit "cancel" button.

**Comment by richvdh** [comment]
This code has been rewritten since 2021
