### ISSUE TITLE
Client cuts numbers at the beginning of a sentence

### ISSUE THREAD

**Issue by Z-Brox** [element-hq/element-web#14621]
### Description

When you write a number (3-9 digits) followed by a dot (".") the client drops all digits but the final two.

### Steps to reproduce

Write into chat: 123456789.
gives: 89

Or: 500.
shows: 00.

![numbers-bug](https://user-images.githubusercontent.com/22732856/87862480-f39de780-c950-11ea-91d3-98794800adf8.png)

### Version information

- **Platform**: web (in-browser) or desktop? Desktop

- **OS**: Debian Buster, confirmed by chat partner with client under iOS and MacOS X.
- **Version**: 1.7.1

**Comment by Me4Linux** [comment]
Correction: numbers are not dropped, but shifted to the left.

**Comment by t3chguy** [comment]
Screenshot for dev:

![image](https://user-images.githubusercontent.com/2403652/87872458-b406e800-c9b0-11ea-8541-9c21e57805d7.png)


This is because the left-padding is fixed to 2em so doesn't allow list integers higher than that
(+ the fact that CommonMark interprets `500.` as a list)

**Comment by Me4Linux** [comment]
Thank's for the confirmation, t3chguy.
Devs: is it possible to change the behaviour to start two lines with numbers instead of one before a list is supposed? Like:
1. Text.
2. Now we're sure that's a list.

**Comment by t3chguy** [comment]
That would be a query for https://commonmark.org/ as that is the markdown parser used

**Comment by Yoric** [comment]
So, this could be fixed by a CSS change, right?

**Comment by t3chguy** [comment]
Yes

**Comment by chagai95** [comment]
Anyone planning on fixing this? Would be nice to know where this is on the roadmap 🙈

**Comment by dkasak** [comment]
> Devs: is it possible to change the behaviour to start two lines with numbers instead of one before a list is supposed? 

> That would be a query for https://commonmark.org/ as that is the markdown parser used

This isn't strictly related to CommonMark, as this is primarily a question of whether we consider a particular message to be Markdown at all. We already treat certain messages as plain text instead of Markdown, such as when they only contain text nodes or disallowed HTML tags.

I think the suggested rule of only considering something to be a list when it has two items is a good one and would increase usability. At the very least, we should consider lists with a single *empty* item to be a plain text (i.e. non-Markdown) message. I'd volunteer to implement this as it has been irking me for some time. This would be a separate change to the proposed CSS fix above.

**Comment by SimonBrandner** [comment]
> I'd volunteer to implement this as it has been irking me for some time

Sure, go ahead!

**Comment by neer17** [comment]
@SimonBrandner Since there is no activity on this for a month, so can I work on this?

**Comment by SimonBrandner** [comment]
> @SimonBrandner Since there is no activity on this for a month, so can I work on this?

I am a bit unsure atm, isn't this solved by https://github.com/matrix-org/matrix-react-sdk/pull/6833?

Also, no need to ping me specifically

**Comment by dkasak** [comment]
Just to clarify, no, matrix-org/matrix-react-sdk#6833 doesn't fix this, except as a side-effect in a particular sub-case. That PR makes Element Web stop treating messages such as this one as Markdown:

```
2021.
```

This has the side-effect of sidestepping the current faulty formatting. However, messages such as the following one are still treated as a Markdown list:

```
2021. foo
```

Since the CSS for Markdown lists is still incorrect, the number would still be cut off in this case. So @neer17 if you'd like to take a stab at fixing this, go for it.

**Comment by neer17** [comment]
I would take a shot at this one.

**Comment by sakshi-0206** [comment]
Hey @dbkr @SimonBrandner 
I am an Outreachy applicant and would like to work on this issue. Can you assign this to me?

**Comment by ttheshreeyasingh** [comment]
@sakshi-0206 If you're not currently working on this issue? Can I be assigned this issue as well?

**Comment by t3chguy** [comment]
Clearing assignment as per https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues - anyone is welcome to work on this, once you have a draft feel free to mention it here and we can set assignment then!

**Comment by BalanaguYashwanth** [comment]
Hello @Me4Linux,

I see some PR's had raised for this issue. Can you check if it is solved this issue ?

**Comment by Me4Linux** [comment]
Hi, @BalanaguYashwanth 

I'm using V1.11.23 now. Still got the problem here that numbers up to 9 digits are truncated. 10 or more work. For example I write: 123456789.
Element-Desktop shows: 89. (and I see some pixels of the digit "7")
But when I write: 1234567890.
Element shows: 1234567890.

**Comment by BalanaguYashwanth** [comment]
ok

**Comment by ara4n** [comment]
the workaround to this is to override the 2em in the CSS from gfm.css

```css
.markdown-body ol, .markdown-body ul {
    padding: 0 0 0 2em;
}
```

...and I guess do some dirty heuristic to do that automatically the string length of the number is too wide.

**Comment by aditjya** [comment]
is this still open?

**Comment by t3chguy** [comment]
![image](https://github.com/element-hq/element-web/assets/2403652/aec74f68-9de6-4a0e-a3e0-50f8f50662d7)

Yes.

**Comment by aditjya** [comment]
Hi @t3chguy i'm new here can you tell me what is the problem to solve? please..

**Comment by aditjya** [comment]
so i need to make it render all the input digits
right?

**Comment by t3chguy** [comment]
Yes, that would be the solution

**Comment by aditjya** [comment]
This might be my first contribution. I'll try my best!

**Comment by shadow-identity** [comment]
Happens on iOS client: 
- peer type: `46)` and sends the message using Element for iOS 
- peer doesn't see the sent message
- I see the message, but I what I see is `46.`
- In the "View Source" dialog I see:
```json
{
  "content": {
    "body": "46)",
    "format": "org.matrix.custom.html",
    "formatted_body": "<ol start=\"46\">\n<li></li>\n</ol>",
    "msgtype": "m.text"
  },
  "room_id": "xxx",
  "type": "m.room.message"
}
```

**Comment by t3chguy** [comment]
> Happens on iOS client:

@shadow-identity https://github.com/element-hq/element-ios is the repo for iOS issues.

**Comment by sarans-h** [comment]
Is the issue fixed??

**Comment by dkasak** [comment]
It's not.
