### ISSUE TITLE
Same user keeps appearing as "Unable to decrypt"

### ISSUE THREAD

**Issue by sourcejedi** [element-hq/element-web#25031]
### Steps to reproduce

We have a small room.  A few times, Sheena's messages (and only Sheena's) have appeared as "unable to decrypt" to other users, and we've had to fix it.  I think leaving the room and being re-invited sorts it out fine.

(I asked about this in the community support, and they pointed out Sheena could probably use `/discardsession` instead of needing to be re-invited).

Now it has happened a couple of times in the past few days.  This is more often than before.  Though, Sheena might have had slightly different usage in these days, so that's not necessarily a brand new bug.

#### What did you expect?

"unable to decrypt" doesn't happen, unless we messed around with the settings or something.

And if it does happen, we want it to happen less often than a couple of times in a few days :-).

### Operating system

Linux (Fedora 37 Workstation)

### Browser information

firefox-111.0.1-1.fc37.x86_64

### URL for webapp

https://app.element.io/#/room/!IgctDrIJMLgFNGjBuB:matrix.org

### Application version

Element version: 1.11.27 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by sourcejedi** [comment]
I believe I have sent debug logs from my Element Web (software versions as above), my Element Android, and from Sheena's Element Desktop on MacOS.  Sheena is not sending the messages from her Macbook, but the Element Desktop there is able to show all of her messages.

**Comment by sourcejedi** [comment]
So I should probably say where she *is* sending messages from, huh :-).  Sheena is mostly sending from Element on Android, a Nokia 5.4.  I don't have access to that device right now.

**Comment by mmulhearn** [comment]
My small group (4 people) also see this a lot. Seems to occur when switching between being on PC for a while, then moving to mobile (doesn't seem to matter if it's iOS or Android; happens to both) and vice versa. Sometimes pulling keys from the other device works, sometimes it doesn't. Can be very frustrating.

**Comment by sourcejedi** [comment]
Hum.  Previously, it has stayed broken for a long time, before we fixed it.

The last failing messages are two from Sheena on the 2nd of April.

Following those messages, Sheena has succeeded in sending messages from the same device (Android phone).  I'm submitting logs now, but I don't know if they'll be useful from that long ago.

**Comment by ParzivalWolfram** [comment]
I'm having the same issue with a member in my group, but `/discardsession` and reinviting didn't fix the issue. I have had the affected user send logs as well, to add to the pile.

**Comment by richvdh** [comment]
https://github.com/element-hq/element-meta/issues/245

**Comment by sourcejedi** [comment]
FWIW, we haven't had this problem recur. Thanks all.
