### ISSUE TITLE
Element freezes or crashes when too many voice messages are in a chat

### ISSUE THREAD

**Issue by AlexanderBabel** [element-hq/element-web#26239]
### Steps to reproduce

1. Create an encrypted chat with a few voice messages. I am not sure how many it takes but I guess 30+ is a good start. Each of them should have a length of more than one minute (I use a WhatsApp bridged chat)
2. Open the chat on Element Desktop
3. The app tries to fetch all voice messages and starts to lag (no or slow UI interaction) or crashes with a white screen
4. Reopen Element (and try to open another chat as fast as possible to prevent another crash)

#### What did you expect?
The chat should be responsive and render only voice messages that are on-screen

#### What happened instead?
Slow chat loading and an app crash

### Operating system

macOS (13.4 Macbook Air M2)

### Application version

Element version: 1.11.34 Olm version: 3.2.14

### How did you install the app?

Element Website

### Homeserver

Synapse 1.86.0

### Will you send logs?

Yes

**Comment by ivy-reps** [comment]
> The problem is that we are currently loading all files into memory: https://github.com/matrix-org/matrix-react-sdk/blob/491b43ef095f6a174755e9e8977218bfe52b98fa/src/components/views/messages/MAudioBody.tsx#L54
> 
> [`sourceBlob` is already a „lazy value“](https://github.com/matrix-org/matrix-react-sdk/blob/491b43ef095f6a174755e9e8977218bfe52b98fa/src/utils/MediaEventHelper.ts#L34). But with the code linked above it will become non-lazy.
> 
> I would say a solution can be to extend `Playback` to work with lazy values as well and then pass down the lazy values. A difference then would be the decryption error handling. Playback needs to provide error feedback and the tile should display it.

seems so, but I'm not sure that this was resolved, and to me that issue is critical because I'm not bale to use Element on Desktop. Immediately it is takes all RAM and I'm seeing white background in Element Desktop Window. And I'm forced to remove all voice messages to make it to work.

**Comment by MartenKahr** [comment]
Still seems to be happening: I can produce a consistent OOM crash of element-desktop by scrolling up to a part of chat history where someone quoted a series of uploaded audio files in quick succession. Memory usage spikes to 6.1GB (out of my computer's 8GB of RAM, and compared to a "normal" of around 100-300MB) and the chat view starts lagging as I do anything (scrolling, swapping rooms etc.) a couple seconds after seeing the quoted audio files. After about 5 to 10 seconds of the stuttering state, Element starts showing only a blank white screen and becomes unresponsive. Element did drop the excessive RAM usage in the unresponsive state after about a minute, but remained unresponsive for about five minutes before I decided it probably wasn't going to recover and killed it.

**Comment by sosnik** [comment]
Believe me, physical RAM is not the issue. It still crashes even with 128GB
and I 100% don't have 128GB of voice messages.

**Comment by MartenKahr** [comment]
Oh, definitely not. There's no way five or six sub-10-minute mp3 files are 6GB either. Something about audio uploads in quick succession (whether they're voice messages or something else) causes Element to fill all memory it can grab with... something it fails to use or release, and crash when the system inevitably stops giving it more. That said, I've done a bit more testing. I've let it stay on the unresponsive whitescreen for a good 30 minutes, and it's safe to say element doesn't recover gracefully from whatever happens here, even if it does release the crazy peak memory allocation pretty quickly after hanging. I've also managed to capture this during the peak of memory usage:

![element_memory_map](https://github.com/element-hq/element-web/assets/15198562/773c478a-9b84-4e07-8397-b6f55cbd7ab2)

Whatever it's doing, it's clearly trying to allocate a downright unreasonable amount of RAM for whatever it's trying (and failing) to do when it encounters that part of room history with the quoted audio uploads. If anyone has suggestions for any useful testing/logging I'm not an advanced enough of a user to think of on my own, let me know and I'll try and do it, since I can reproduce the issue on demand just by scrolling up in a particular room.

**Comment by YourSandwich** [comment]
Same issue for me, 2 years of voice message history has about 3gb in size. I have exactly the same behavior as described here, but it works in the WebBrowser version of Element. Other Matrix Clients are unaffected.

**Comment by ivy-reps** [comment]
Here we go!

**Comment by ivy-reps** [comment]
YES THAT WORKS! YEEEEEEEEHHHHHHHHHHAAAAAAAA!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by MartenKahr** [comment]
Desktop client still stutters and tries to hog a whole lot of memory (see behavior in the memory maps picture from my Apr 7 post; still happening, but stops at 32GiB) when a lot of audio files in quick succession are uploaded, but the client doesn't soft-crash into a broken state anymore.

**Comment by t3chguy** [comment]
This is still a problem

**Comment by KPKoch** [comment]
Still a problem. I do have some nearly audio only contact and it just kills the window within chromium.
On a 5950 with 16 cores and 64GB ram....

While the solution seems f§U("§$ simple: give me a toggle, to disable waveform analytics - problem gone!

**Comment by dbkr** [comment]
We just chatted about this as it's considered p1 but we haven't touched it in a while. We suspect this may not be a problem too much in practice because most clients send audio messages with precomputed waveform data nowadays which would probably not trigger this problem.

We hope to use some maintainer time to confirm this soon and either:
 1. Serialise the waveform generation (possibly also cache them)
 2. or, potentially don't display waveforms at all for audio messages that don't come with waveform data. We'd need to look at what clients don't send them and what we'd be dropping support for.

**Comment by zhiyong5** [comment]
The problem persists as of July 30, 2026.
