### ISSUE TITLE
Bad scrolling performance (lag) in room list

### ISSUE THREAD

**Issue by fblaese** [element-hq/element-web#28606]
### Steps to reproduce

Scrolling in the room list is slow and laggy. Many partially rendered frames.
Requires a few joined rooms, the lag gets worse with more unfolded/visible rooms. I start noticing it with around 50 visible rooms.

Known good version: 1.11.81
Known bad versions: 1.11.85, 1.11.86

I can provide futher assistance or logs, if this issue is not easily reproducible.

#### What did you expect?
Smooth scrolling performance with no dropped frames.

1.11.81: ![Screenshot_20241201_185330](https://github.com/user-attachments/assets/63552094-1d8f-4569-b245-fda221038b88)

#### What happened instead?
Duplicate frames.

1.11.85: ![Screenshot_20241201_185418](https://github.com/user-attachments/assets/ac25b4c6-c6ba-4687-9c7c-12fa0182ba53)

### Operating system

Arch Linux

### Application version

1.11.86

### How did you install the app?

Arch Package

### Will you send logs?

No

**Comment by dbkr** [comment]
Thanks, that's a fairly incriminating profile.

**Comment by scd31** [comment]
I'm experiencing this as well on 1.11.87 on two separate machines (Arch and NixOS)

**Comment by fblaese** [comment]
Any idea which change might have caused this behavior? With many rooms in the list, scrolling is pretty much unusable.

**Comment by fblaese** [comment]
I did further analysis. The problem occured between 1.11.81 and 1.11.82 due to the upgrade of one of these two dependencies:
- `matrix-react-sdk`: 3.113.0 -> 3.114.0
- `vector-im/compound-web`: 5.5.0 -> 6.0.0

Downgrading these to dependencies in element-web 1.11.82 resolves the issue.

In a broken version of element-web, many floating-ui elements are present inside `<body>`, which all have hooks on scroll events, leading to lag. These floating-ui elements have not been present in previous versions of element-web. Many of them seem to be used to display a "Offline" label.

![Image](https://github.com/user-attachments/assets/e4c8e2f8-c76e-4e25-9f6a-d2da4c978167)

**Comment by fblaese** [comment]
It looks like these elements are intended to display descriptions when hovering over the online/offline status indicator of a user. Previously, these elements are generated dynamically when hovering over the indicator, but with recent versions of element-web, the floating-ui is generated unconditionally for all rooms in the list.

**Comment by t3chguy** [comment]
floating-ui is a dependency of https://github.com/element-hq/compound-web it isn't one Element Web uses itself

```
 ~/W/element-web   t3chguy/docker-avoid-tmp $  yarn why @floating-ui/react                                                                                             432ms  Thu Mar 13 14:46:13 2025
yarn why v1.22.22
[1/4] 🤔  Why do we have the module "@floating-ui/react"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@floating-ui/react@0.27.0"
info Reasons this module exists
   - "@vector-im#compound-web" depends on it
   - Hoisted from "@vector-im#compound-web#@floating-ui#react"
info Disk size without dependencies: "780KB"
info Disk size with unique dependencies: "1.4MB"
info Disk size with transitive dependencies: "1.82MB"
info Number of shared dependencies: 3
✨  Done in 0.27s.

**Comment by fblaese** [comment]
The relevant change seems to be https://github.com/element-hq/compound-web/commit/ed4b75f71e415187743fa089cf706eef51927184, which changed the behavior of Tooltips to always be present, but invisible.

Due to this change, the Browser recalculates the positions for all Tooltips, despite them being invisible.

**Comment by t3chguy** [comment]
Fixed by new room list

**Comment by fblaese** [comment]
The new room list has improved things, especially with long room lists. But it still fails to render at the monitors refresh rate, even on modern hardware. Still getting many partially-presented frames.

<img width="2476" height="570" alt="Image" src="https://github.com/user-attachments/assets/2d4ad335-9baf-47c6-aad8-014b4c83c363" />

**Comment by jfrederickson** [comment]
I came looking for this issue after getting switched to the new room list during an upgrade. On one hand, the behavior of the scrollbar itself seems to move more smoothly with the new room list... but on the other hand, the list contents seem to take longer to catch up with the scrollbar's position.

I captured a profile while scrolling:

<img width="1338" height="513" alt="Image" src="https://github.com/user-attachments/assets/118fd837-1f00-43bb-b1ee-7f3edd2ae46c" />
