### ISSUE TITLE
Can no longer shrink the room list

### ISSUE THREAD

**Issue by Asynonymous** [element-hq/element-web#30844]
If anyone else finds this and wants to disable the new look:

1. Type `/devtools`
2. Enable "Developer mode"
3. Go to Settings > Labs 
4. Scroll way down to the bottom and untick "Enable new room list"
 
---

Since the latest update almost half my window space is lost as I can't hide the channel list anymore.

### New:
<img width="737" height="263" alt="Image" src="https://github.com/user-attachments/assets/91b3ef17-15d3-4285-a4ee-bd5b886e1b4d" />

### Disabled:
<img width="849" height="285" alt="Image" src="https://github.com/user-attachments/assets/2a61e599-1954-498b-8519-464af50d921d" />

#### What did you expect?
Previously when dragging the channel list to the left it would shrink to display picture size.

#### What happened instead?
It retains an excessive width which waste screen space.

### Operating system

Windows

### Application version

Element version: 1.12.0 Crypto version: Rust SDK 0.14.0 (c3b7918), Vodozemac 0.9.0

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by anmolnar** [comment]
Thank you for instructions how to disable the new look!

**Comment by rupi-lol** [comment]
Oh. Nice to see it can be disabled!
But honestly having the ability to collapse it back to icons would be preferable.

**Comment by gdvine** [comment]
Thank you! First the misguided, unwanted "Spaces" sidebar that's impossible to disable, and now an uncollapsible Room List. It seems as if the devs here are only using Element for testing, maximized on their screens, rather than real-world use in the corner of the screen. A chat app must be as compact as possible. The Element team's UX humans seem totally unaware of this basic fact.

**Comment by thany** [comment]
Downgrading for the time being.

If anyone's interested where to get previous versions, here you go:  
https://packages.element.io/desktop/install/win32/x64/index.html

For another OS, just navigate to it through "parent directory".

Maintainers: please make sure to fix the issue, because the update notification is more annoyance than excitement until this is fixed. Also, can you please let us know why this problem got to be in the first place? Something must've changed, and nobody bothered to test the UI or something? Or worse, this was done on purpose?

**Comment by kikislater** [comment]
The new Ui is a total fail ! I use it in firefox/librewolf as I don't want to use a chrome base web view. 
This is the url I got after this unwanted update https://app.element.io/?updated=1.12.0 I can not disable it ...

**Comment by chrismitch397** [comment]
Thanks for the method to disable the new room list. I agree with gdvine, the app needs to be as compact as possible in the corner of the screen.

**Comment by de0u** [comment]
On the web client, I had to use a slightly different flow:  first ```/devtools```, then "Settings explorer", type ```feature_new``` in the filter box, click on the pencil, then scroll down and change two instances of ```"device": null``` to ```"device": false```, then "Save settings values".

Maybe someday the new room list code will support collapsing to icons, in which case I guess I'll want to undo this override.

**Comment by thany** [comment]
Ok, downgrading didn't work. The app just updates again, without my goddamn permission. It doesn't understand that when I downgrade it, I do so for a reason. This is very frustrating.

It's good that there's a workaround, but I fear a workaround will just act as a disincentive to an actual solution.

**Comment by craether-nbb** [comment]
> Ok, downgrading didn't work. The app just updates again, without my goddamn permission. It doesn't understand that when I downgrade it, I do so for a reason. This is very frustrating.
> 
> It's good that there's a workaround, but I fear a workaround will just act as a disincentive to an actual solution.

To stop the app from auto-updating, you can overwrite the default update endpoint in your config.
e.g. at MacOS: `~/Library/Application\ Support/Element/config.json`
Just add a record:
```
"update_base_url": ""
```

**Comment by thany** [comment]
> To stop the app from auto-updating, you can overwrite the default update endpoint in your config. e.g. at MacOS: `~/Library/Application\ Support/Element/config.json` Just add a record:
> 
> ```
> "update_base_url": ""
> ```

I'm on Windows, but let's say I can do the same trick there. Surely this will be reset whever I *do* want to update (when the problem is fixed, and/or the workaround is no longer required for a sensible UI). Actually this might be desirable. Or maybe not, that's the point 😀

This is like a workaround to make a workaround work 🤯

I appreciate your input though, don't get me wrong. But man, this is some bollocks.

**Comment by rupi-lol** [comment]
Just a comment for people looking for a solution to the new roomlist defect:

Blocking updates is not a good solution. Chromium and thus Electron and therefore Element frequently get security relevant updates. Since any chat program processes input from unknown sources by it's very nature it is never a good plan to run outdated versions.

**Comment by Half-and-Xat** [comment]
On little screens as my pocket computer (running Debian based OS) it uses exactly 50% of the screen space while the actual chat has not even enough space to get displayed properly as before. And since chat box is wasting a huge amount of space, there is only space for 4 or 5 sign (depending on sign sizes).

Maybe a designer should work out how Element can work on every screen size and with any input method (mouse/keyboard/touch) make and keep design language consistent. Currently it feels that one hand has no clue what the other hand is implementing on how elements (as buttons, sliders, ...) should look, feel and behave. But for the moment it would be enough and very helpful to get the small room list available again.

**Comment by Taranchul** [comment]
I second this, I want the old room/people list back from pre 1.12.0 that you could shrink to only the icons and show the filter groups (Favorites, People, Rooms) one below the other. 

My chat window is only 1/3 of my screen wide and now the list takes 1/2 of it without any means to shrink it any further. 

I hate those GUI "enhancements" that are actual regressions in usability, in this case for anyone who has a slim chat window. I'd like to have an option for the old list GUI _without_ having to enable dev mode.

**Comment by whezzel** [comment]
I appreciate the steps to disabled this new, awful "feature". If anyone knows how to disable the terrible, unwanted Spaces Sidebar, that would be great too.

**Comment by RasheedAZ** [comment]
Thanks for the temporary workaround - I hope they make it collapsible, perhaps even merge the two sidebars. 

I'm using this on a Librem 5 Linux phone (with postmarketOS and PureOS) and an uncollapsible sidebar makes Element Desktop completely unusable in portrait mode.

**Comment by Ayandaftary** [comment]
Both sidebars should be merged and be collapsible, this is awful UX design

**Comment by thomasza92** [comment]
Can any devs answer why the UI is objectively getting worse in new updates? Removing the ability to collapse a sidebar is not a feature or an improvement, it's a regression.

**Comment by nt8r** [comment]
> Can any devs answer why the UI is objectively getting worse in new updates? Removing the ability to collapse a sidebar is not a feature or an improvement, it's a regression.

It seems like this comment was incorrectly hidden as "abuse". I don't think it's abuse of GitHub or the Element developers to note that the UI is definitely worse with this change, given how many folks are complaining. It's not abusive to ask about the reason for such changes, despite how frustrating it can be to receive negative feedback.

**Comment by kikislater** [comment]
Agree, Ui became weird and every guy involved in element totally don't care. This is even more worse!!!

**Comment by SoftwareSchlosser** [comment]
+1 for a collapse feature :)

**Comment by notfatnotfunny** [comment]
+1

**Comment by anmolnar** [comment]
@t3chguy Are u guys going to address this issue in a future version? What's the plan?

**Comment by t3chguy** [comment]
@anmolnar if it wasn't going to be addressed then this issue would have been closed.

**Comment by anmolnar** [comment]
> [@anmolnar](https://github.com/anmolnar) if it wasn't going to be addressed then this issue would have been closed.

That's clever, but I think providing updates regularly and keeping the users in the loop works better.

**Comment by t3chguy** [comment]
There will be an update, when work starts on it, no point spamming the feed with "No update yet, we're too busy with other things". Contributions welcome of course.

**Comment by anmolnar** [comment]
> There will be an update, when work starts on it, no point spamming the feed with "No update yet, we're too busy with other things". Contributions welcome of course.

I totally understand it, but a simple "request accepted" would have been enough. Good to know for future reference that keeping the ticket open means the same. It wasn't obvious for me, but maybe it's just me. Thanks.

**Comment by kikislater** [comment]
Revert back the weird PR in that case if the team don't have time ... Leaving this as a draft for all users is not cool !!!

**Comment by t3chguy** [comment]
> Revert back the weird PR in that case if the team don't have time ... Leaving this as a draft for all users is not cool !!!

As it happens, the product team make decisions for what we work on and in what order, not yourself. You're welcome to revert it in your own fork though.

**Comment by Half-and-Xat** [comment]
@t3chguy: You are right in what you write. It is your teams project and your team can order in the priority you want. Also it was clear what keeping issue open means (for those who are familiar with Git). But you probably underestimate why people are upset about this specific issue.

We are speaking about something that was working fine previously and now it is a regression that makes Element just completely unusable for some people and a bad experience for others. Such a regression is usually fixed within the next patch on most other projects, but here nobody knows if it is fixed next week or next decade. As I said before, it is your project and your decision, but it means a lot to the minority of people that is highly affected by this. I am using Element on desktop and pocketcomputer and while I don't care on desktop, I want to show you how it looks on my little Linux device before and after:

<img width="360" height="720" alt="Image" src="https://github.com/user-attachments/assets/0d9592d5-1fda-4048-a8e2-0dda23098470" />

<img width="360" height="720" alt="Image" src="https://github.com/user-attachments/assets/daea13af-3d4e-4718-bfd6-7d8dbc21f2f5" />

Some elements as the header buttons on the right are pushed out of the screen, text is nearly unreadable and so on. I know, you do not official support those devices, but it worked flawless before, otherwise I would not even have had consider to use Element there. And other people are using tablets and other devices and still have similar issues. It is not just a minor issue (other than labeled) where people are more upset than they should be, being upset has a strong reason here. It would be nice if you could discuss internally if such regressions could get a higher priority.

Anyway, I also understand your points and will not argue here any further. And you know our arguments now and I think you understand us, too. So need to continue spamming you (hint for others).

**Comment by t3chguy** [comment]
> pocketcomputer

This isn't supported hence no fix was made "within the next patch"

> Desktop OSes means macOS, Windows, and Linux versions for **desktop devices**

https://github.com/element-hq/element-web#supported-environments

We are looking at improving small screen support for accessibility reasons and this will be one of the things that is tackled, but even so, see the support policy

**Comment by whezzel** [comment]
By that logic, laptops aren't supported platforms either, becuase they aren't desktops. Its running a desktop Linux os, therefore, it should be supported, even if its got a small screen. I agree with @Half-and-Xat, usually regressions like this are fixed pretty quickly in other projects, but here it seems like the devs don't care. I think a simple acknowledgement of whether or not y'all plan to fix this regression would go a long way.

**Comment by gree7** [comment]
Btw. I am running a desktop PC with Linux, but I use only half of my screen and in such case I have similar problem as @whezzel.

**Comment by t3chguy** [comment]
> By that logic, laptops aren't supported platforms either, becuase they aren't desktops. Its running a desktop Linux os, therefore, it should be supported, even if its got a small screen.

If you think it needs clarification you can open a discussion in https://github.com/element-hq/element-meta - but we consider desktop devices to mean those you operate with a physical keyboard and mouse, or accessible technologies approximating those input methods, with a full sized screen. Touchscreens are not inherently supported but work to some degree. Pocketable devices are considered Mobile and not supported at this time, though we will never go out of our way to prevent them from working.

> usually regressions like this are fixed pretty quickly in other projects

It isn't a regression, but in any case you are always welcome to use those other projects instead or maintain a fork. Ultimately Element Web is an open source project led by a commercial entity which has to fulfil its customer commitments first to pay the bills.

> A software regression is a type of software bug where a feature that has worked before stops working correctly.

This could even be argued as a feature request. New room list lacks a *feature* you desire. Its not like we went and caused a bug in an existing thing.

**Comment by whezzel** [comment]
A collapsible sidebar that used to work and no longer works is what I would consider a bug, unless you're saying it was an intention design choise to waste more screen real-estate by removing the ability to collapse it. 

I disagree that it should be a feature request, instead of a bug report, becuase it used to be a feature that this application had, that no longer works. Are you saying that the collapsible sidebar was a bug before, and y'all finally fixed it? What you are saying makes no sense. Do you not realize that the sidebar used to collapse?

**Comment by t3chguy** [comment]
If the sidebar was changed such that it only supported a collapsed state would you also consider that a regression? Would you then say any UI change that you don't like is a regression? It is a design choice, which ultimately was gone back on due to community feedback.

**Comment by whezzel** [comment]
Yes. If a collapsible sidebar was unintentionally changed so that it could only be used in a collapsed state, and no longer expanded, I would consider that a regression and a bug that needs to be fix. Would I notice? No becuase I don't use it in an expanded state, becuase it wastes space. 

All UI changes as bugs? No. Is it an intentional design change? Not a bug. Is it an intentional design change with unintentional feature regresssion? Yes, that's a bug. There's nuance, but clearly you don't understand that. 

The issue I have is that this was a feature this app had, that was removed and it was not documented anywhere in the change logs. If this was an intentional change and the collapsible sidebar is something y'all are no longer going to support, then it should've been documented. 

The only thing doccumented is that the new room list is now the default with a link to the PR (https://github.com/element-hq/element-web/pull/30640) which also doesn't mention the sidebar is no longer collapsible, but plenty of people noticed and mentioned it on that PR. 

Again, intentional change (new room list) with unintentional feature regresssion (room list no longer collapsible) == bug.

**Comment by t3chguy** [comment]
> Yes. If a collapsible sidebar was unintentionally changed so that it could only be used in a collapsed state, and no longer expanded, I would consider that a regression and a bug that needs to be fix. Would I notice? No becuase I don't use it in an expanded state, becuase it wastes space.

Right but it is the designers who define whether what the bar looks like in all of its states. If they decided that the new room list is only ever the collapsed-like one with only avatars then that is simply the new design and not a regression.

> Is it an intentional design change with unintentional feature regresssion? 

It was intentional, the original designs explicitly had no collapsed state and that was the plan to keep, the designers simply changed their minds after hearing feedback. 

> Again, intentional change (new room list) with unintentional feature regresssion (room list no longer collapsible) == bug.

Again, it was intentional, it matched the designs as drawn by the team of designers, and collapsibility was discussed and rejected at the time. It wasn't until it was made default that there was any noise about it (such as you mention in the PR, and this issue itself) even though it was available on develop.element.io for many months prior.

**Comment by whezzel** [comment]
You're only demonstrating that you don't understand nuance.

>> Yes. If a collapsible sidebar was unintentionally changed so that it could only be used in a collapsed state, and no longer expanded, I would consider that a regression and a bug that needs to be fix. Would I notice? No becuase I don't use it in an expanded state, becuase it wastes space.

>Right but it is the designers who define whether what the bar looks like in all of its states. If they decided that the new room list is only ever the collapsed-like one with only avatars then that is simply the new design and not a regression.

This would be an intentional change. They intended to make the sidebar only disaplay icons in a collapsed veiw with no option to expand it. Not a regression.

>>Is it an intentional design change with unintentional feature regresssion?

>It was intentional, the original designs explicitly had no collapsed state and that was the plan to keep, the designers simply changed their minds after hearing feedback.

Now you're just trying to gaslight everyone in this thread that utilized the collapsible feature of the sidebar by stating that it was originally not collapsible. I've been using element since the beginning. Back when it was called Riot. I feel like its been close to 10 years that I've been using it. Its always had a collapsible sidebar.

>>Again, intentional change (new room list) with unintentional feature regresssion (room list no longer collapsible) == bug.

>Again, it was intentional, it matched the designs as drawn by the team of designers, and collapsibility was discussed and rejected at the time. It wasn't until it was made default that there was any noise about it (such as you mention in the PR, and this issue itself) even though it was available on develop.element.io for many months prior.

Why not document these intentional design changes to avoid threads like this being created as "bugs"? If this was a documented, intentional design choice, this whole thread could've been opened as a feature request to return a widely used feature that was removed. There's a reason why basically every chat platform has a collapsible sidebar..... people want, and use it.

>though it was available on develop.element.io for many months prior.

Casual users like myself don't use the test instances like this. I use it to chat with friends. I dont expect major design changes like this that change how I have to use this app on my computer. I use it in a small window.... not fullscreen.

I'll be done after this post. Clearly, y'all don't care about the feedback the community has provided. You acknowledge that people said this was not a wanted change in the PR before it was implemented and rather than have good faith discussions with the community about it  y'all moved forward with this terrible design choice. Now we have this thread with more people stating it's an unwanted change and rather than acknowledge whether or not this is something y'all plan to fix, we are sitting here arguing the nuance of what is and isn't a bug.

In the future, maybe clearly document the changes y'all are making instead of using vague descriptions that would require knowledge of internal discussions to know the full details.

**Comment by langleyd** [comment]
Thanks all for your feedback here.
The current default implementation of the room list is intended as a stepping stone to a new room list experience that is not yet complete.
Apologies if that intermediate state has evidently been causing some pain to users.

The next iteration of features we are considering are detailed [here](https://github.com/element-hq/element-web/issues/31207).  It is still being finalised be we are ramping up to work on it. I'm not quite sure why the [show/hide/resize issue](https://github.com/element-hq/element-web/issues/31536) was closed but we do still plan to start work on it soon.

I can update when we have something to share.

**Comment by t3chguy** [comment]
> This would be an intentional change. They intended to make the sidebar only disaplay icons in a collapsed veiw with no option to expand it. Not a regression.

They did the exact same thing but instead deciding it should no longer have an icons-only mode as it was not accessible and in their view not usable.

**Comment by whezzel** [comment]
Thank you @langleyd. This is what shouldv've been posted by @t3chguy instead of arguing nuance that he doesn't understand. 

>They did the exact same thing but instead deciding it should no longer have an icons-only mode as it was not accessible and in their view not usable.

If its intentional, document it. If it's not documented, how do you expect people to know it was intentional? As a casual user, all I know is that the sidebar used to be collapsible, but now it's not.

**Comment by t3chguy** [comment]
That's more of a suggestion for product/design folks rather than developers, your feedback is best as a discussion on element-meta where they might see it.

Also worth noting as per https://github.com/element-hq/element-web/issues/31536 the icons-only view is not planned to return, you'll just be able to hide the room list entirely. At a later stage you may have mutually exclusive views more akin to mobile at smaller viewports, where you can only see the room list or the timeline at a time.

**Comment by langleyd** [comment]
Resizing to a narrow view I think is still being considered. Icons and notifications badges visible at a minimum, but it’s not finalised.

**Comment by t3chguy** [comment]
@langleyd where is that happening because that is not in the [public](https://github.com/element-hq/element-web/issues/31536) nor [private](https://github.com/element-hq/wat-internal/issues/292) issues

**Comment by whezzel** [comment]
>That's more of a suggestion for product/design folks rather than developers, your feedback is best as a discussion on element-meta where they might see it.
>
>Also worth noting as per https://github.com/element-hq/element-web/issues/31536 the icons-only view is not planned to return, you'll just be able to hide the room list entirely. At a later stage you may have mutually exclusive views more akin to mobile at smaller viewports, where you can only see the room list or the timeline at a time.

I know I said I was done, but I just have to respond. You clearly don't know how to interact with the public, and should stop. I can only assume you are being intentionally obtuse at this point.

If an intentional feature change isn't documented, and all discussions about removing a feature are private, how do you expect people to know it was an intentional change? If I had know this was an intentional change, I would've opened a discussion about it instead of responding to this issue that someone else opened.

Instead it was discussed in private and implemented with out any mention or documentation, so as a user without knowledge of private, internal discussions, I can only assume it was unintentional.

**Comment by t3chguy** [comment]
> If an intentional feature change isn't documented, and all discussions about removing a feature are private, how do you expect people to know it was an intentional change?

I have no control on whether product/design open internal or external issues, or how they document their work (currently only via a private Figma design)

By either assuming that it is intentional, or asking in the room, or opening an issue such as this one and being told either way.

> Instead it was discussed in private and implemented with out any mention or documentation, so as a user without knowledge of private, internal discussions, I can only assume it was unintentional.

Being mentioned or documented in the implementation PR as you seem to expect it to be isn't helpful to the vast majority of users. Most of our users never touch Github. So what you seem to be asking for, if you truly care about the average user rather than yourself, is something like https://github.com/element-hq/element-web/issues/26092 or https://github.com/element-hq/element-web/issues/25020

**Comment by whezzel** [comment]
Please stop @'ing me. I keep unsubscribing from this and you keep dragging me back in.

This is a rhetorical question. Where does this changelog mention that the room list no longer being collapsible is an intentional change? https://github.com/element-hq/element-web/releases/tag/v1.12.0

It's nice that y'all are looking to expand that changelog to more than just develop, but if you don't document intentional changes like this in the changelog, then you still run into the same issue of average user not knowing if a change is intentional or not.

>By either assuming that it is intentional

Again, another rhetorical. So I'm just supposed to assume all changes are intentional? So just assume all changes are intentional whether they are or aren't? That just sounds like you don't want bug reports. Again, rhetorical. Please don't @ me, I want to leave this conversation.

**Comment by t3chguy** [comment]
I have not `@` mentioned you a single time, ever. The only people that have been `@` mentioned in this entire issue are myself and David. 

You seem to have a selective reading issue, maybe ask for someone's help to read https://github.com/element-hq/element-web/issues/25020 once again

**Comment by langleyd** [comment]
Please everybody, let's keep the discussion respectful and focused on the product behaviour. The feedback here is noted, and we’ll share updates when there’s something concrete to communicate.

**Comment by anmolnar** [comment]
> Please everybody, let's keep the discussion respectful and focused on the product behaviour. The feedback here is noted, and we’ll share updates when there’s something concrete to communicate.

Well said.

Would you guys please kindly update this ticket when the issue is fixed in a release?
Letting watchers know about the workaround is no longer needed would be much appreciated. Thanks!

**Comment by t3chguy** [comment]
This got fixed. The room list is now shrinkable.

**Comment by kikislater** [comment]
After 7 months I think you loose a ton of users ...

**Comment by t3chguy** [comment]
> After 7 months I think you loose a ton of users ...

It was fixed early March. Analytics show otherwise but you're welcome to keep speculating.

**Comment by rupi-lol** [comment]
This is not really a good fix. Now we either have a very large room list or none, the stated usecases in this issue are not really fixed.

**Comment by Half-and-Xat** [comment]
I just found out yesterday and wanted to comment today (so funny that you were just few hours faster). 

Feedback:
Closing the panel doesn't feel nice via touchscreen, but it is possible. That is an improvement over what it was before the September. But it always closes completely. No choice of "just keeping room-icons visible". So unlike before I **have** to close and open it every time I want to read another room. That is not so great. But hiding it completely is also not bad in general, because it gives even more space for the chat itself. To show the room again there is an easy to use drag-handle and that works really well.

Overall no perfect solution, but it works. Whoever found time to implement it, thank you.

@t3chguy: Analytics usually don't tell the whole story. Discords age verification nonsense alone lead to more new users on Matrix and Element than people that could not use Element in the meantime. Of course it shows an increase of users, even if all affected users would have left Element (that did not happen).

**Comment by anmolnar** [comment]
Lord, this product gets worse with every release. Any suggestion for an alternative desktop client?

**Comment by kikislater** [comment]
So this is what we get in desktop before modification: 

<img width="655" height="699" alt="Image" src="https://github.com/user-attachments/assets/a8b50bf5-d461-4c31-b2fc-b515958e7fcf" />

And now:

<img width="655" height="698" alt="Image" src="https://github.com/user-attachments/assets/3a6c026f-871f-4ee5-b96a-9bfe0672c4b0" />

Is this the expected behaviour ? It is on or off, before it was possible to see icons, why not now ?

**Comment by Taranchul** [comment]
The OP's expected behaviour was "when dragging the channel list to the left it would shrink to display picture size."

This is still not possible, so this issue isn't fixed.

Please never remove the Labs option to disable the new room list. I'd stop using Element if that ever happens. I want a room list of only icons like before that takes the least amount of space, but so I can still see the rooms and their new message count, and quickly switch between them.

The new list can still be resized to a degree, so I don't understand why not just allow that up to only the icons like before?!

edit: some small corrections.

**Comment by thany** [comment]
Good thing the new room list is still in beta, because I would expect the room list to collapse (which it does) and merge with the sidebar (which it doesn't).

Also the little `||` is distracting visual noise. It should collapse completely, to 0 pixels wide. Users still have the border on the right of the sidebar to grab onto, to drag the roomlist back to being visible.

At least it stays collapsed, which the current (non-beta) room list still doesn't do. So we still have a choice between two broken room lists. One is "stable" but feels abandoned, the other is in beta (hence why it's in labs) and feels like beta as well.

Why can't we just have one that works, instead of two that are broken?

**Comment by Half-and-Xat** [comment]
@thany please give a look into #33288 that I created, so we can discuss a solution that fits all of us. I think I covered most points well enough, but if you have constructive ideas or complains, please leave a comment below the other issue. I would especially like to know if you agree with my `| |` (drag-handle) design. But please answer in the other issue-thread.

For those who are upset, just in case: please keep frustration and non constructive complains out of the other thread. We all want to have a good solution and that requires a healthy discussion.

**Comment by anmolnar** [comment]
> For those who are upset, just in case: please keep frustration and non constructive complains out of the other thread. We all want to have a good solution and that requires a healthy discussion.

_If ain't broke, don't fix it._

Revert to the original completely and problem solved.

**Comment by t3chguy** [comment]
@anmolnar you are of course more than welcome to fork and maintain whatever "fixes" you like. The design team made a decision, backed by the product team to make a swathe of changes to the left panel, some of which are done and many of which are still in the pipeline. Ultimately if you do not like it, you can keep complaining about the free project you are making demands of into the ether, but not here.
