### ISSUE TITLE
`web+riot` registerProtocolHandler

### ISSUE THREAD

**Issue by lukebarnard1** [element-hq/element-web#4940]
This would be required were we to want a better `matrix.to` experience. `matrix.to` would also need modifying so as to point to `web+riot://#/room/!bla/$bla` instead of `https://riot.im/app`.

**Comment by lampholder** [comment]
I don't understand this I'm afraid - does this mean matrix.to riot links could open in existing riot instances rather than starting a new instance? If so :+1: :+1: :+1: :+1: :+1: :+1: :+1:  :smile:

**Comment by lukebarnard1** [comment]
Yep, that's exactly it. Although I wonder if we should do `web+matrix` instead? As a general way to swap to a matrix web-based client? Probably not that much to gain from it, so `web+riot` is sufficient.

**Comment by aaronraimist** [comment]
Is this fixed by matrix-org/matrix-react-sdk#2272?

**Comment by turt2live** [comment]
Not entirely. That PR makes it easier to navigate links but doesn't solve the problem outlined here

**Comment by bkil** [comment]
Duplicate/superseded by https://github.com/vector-im/element-web/issues/16875

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/element-hq/element-web/issues/16875
